[package]
name = "urx"
version = "0.1.0"
edition = "2021"
authors = ["hahwul"]
description = "A tool to fetch known URLs for domains from Wayback Machine and Common Crawl"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
futures = "0.3"
indicatif = "0.17.7"
url = "2.5.0"
rand = "0.8.5"
scraper = "0.18.1"
